### ISSUE TITLE
Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by OscarJohnson6** [OscarJohnson6/IndieProject#5]
Hi, @pawaitemadisoncollege the project is ready for checkpoint 2. 

Some side notes about certain things I did:
- I found combining the SQL scripts I wrote to work best for the cleandb.sql since I had foreign key constraints the dumpsql didn't fully work.
- I added my DAOs to an Indentity interface so that the GenericDao could reference the getId method, I also thought it made sense since they all have an Id. But I am also not sure if it's unnecessary.
- I copied and pasted all the record unit tests because they are all the same and work/pass. I didn't mean to when I was first inserting data I was just being lazy and had the other records have the same data. I tried to think of a way to loop through the record classes in a record unit test but then I just thought it was just simpler to test for each one. I also know I could improve on testing more values I just struggle knowing what would be considered too excessive testing compared to too little.

- I also had to change my database properties file to the AWS URL because when I ran all my unit tests it would refresh the local database but not the AWS (refresh is the cleandb). I noticed this when running my user tests as it would insert a user as a test and the last test got all the users but it was 10 instead of 9 and when I ran it again it was 11. So I am just curious if that is fine to do because I thought/think the unit tests are just supposed to be on a local database instead of the online/AWS one. I am also curious if there is a way to not have the unit test run each time Tomcat is run because it can take a while with all the unit tests and the connection to AWS.

**Comment by pawaitemadisoncollege** [comment]
Hi @OscarJohnson6! You asked about the database. I see you ideally having 3 databases: 1 local for unit testing, 1 local for local development, and 1 in aws for your deployed application.  Only the local unit test database should be cleaned and reset when the unit tests run.  As far as the test running every time you deploy, that is typical, but you can turn them off in the maven view. There's a button that looks like the "no" symbol circle with a line through it - if you hover over it, it reads "toggle skip tests mode".  Be careful with this - it's easy to forget you turned the tests off, and you could make some breaking changes without realizing it. Let me know if that answers your questions!

- [x]  Can you add an image of your ERD so that I can review and provide any feedback (if this is here already and I overlooked it, please let me know). If you don't have a preferred way to create the erd, you can generate it out of the database view in IntelliJ. I think the sequence is right click on the db, then diagrams. I realize I should have been more clear about including this for this CP.

- [x] You mentioned the generic dao, but I don't see that implemented yet. The persistence package looks like it only has entity-specific daos? I shared the generic dao code in slack week 5 channel.  It's a nice way to get rid of the duplication across daos and meet best practices. Note that your entity-specific tests will remain, they will just use the generic dao instead.

 - [x] You've been doing a good job updating your time log and project plan as you complete work. Related to the plan, if you haven't reviewed and updated your plan recently for the final 8 weeks, this would be a good time to do that, since you now have all the learning on new topics needed for the project (or will have in the next few days).

- [x] I did some additional poking around in your project - I was excited to checkout the api work that you've done! I noticed that you are using a list of TreeMaps: https://github.com/OscarJohnson6/IndieProject/blob/aa78bf35db518b1a529c08b71015a31f7c312366/src/main/java/fit/app/api/ExerciseNinjas.java#L79-L96. This seems like a great place to use a class to represent the response - in week 8 I demonstrate using the robopojogenerator. You could use it with the response from the ninjas service to create some meaningful classes that will give you a more OO solution that what exists currently. 

I'm going to mark this as "not yet" in blackboard mostly as a reminder to myself that I need to review the ERD yet.

**Comment by pawaitemadisoncollege** [comment]
Oops - one more thing - I forgot to comment on the Dao unit tests.

Your unit testing should also verify the relationships. For example, here: https://github.com/OscarJohnson6/IndieProject/blob/aa78bf35db518b1a529c08b71015a31f7c312366/src/test/java/unitTests/WeightRecordsTest.java#L83-L89. What should happen to the user in this case? After the deleting the weight, should the user still be on the table?  Be sure to test both sides of all the relationships. If I delete a user, what happens to their weight? If I delete a weight, what happens to the user. Make sure what should happen, does happen.

**Comment by OscarJohnson6** [comment]
Hi, @pawaitemadisoncollege.

- Here is my [ERD diagram](https://github.com/OscarJohnson6/IndieProject/blob/main/Mockups/mysqlDesign.png), I should have and plan to reorganize the files in the mockup folder so that it's better labeled and easier to find.

- Here is my [Generic dao](https://github.com/OscarJohnson6/IndieProject/blob/main/src/main/java/fit/app/database/GenericDao.java#L79), and the line on why I used the interface for the getId method to return the id after an insert.

- I updated the [height delete](https://github.com/OscarJohnson6/IndieProject/blob/main/src/test/java/unitTests/HeightRecordsTest.java#L88-L105) unit test to test the user values. However I had trouble with my [user delete](https://github.com/OscarJohnson6/IndieProject/blob/main/src/test/java/unitTests/UserAccountsTest.java#L83-L99) unit tests because I kept getting an attribute error but I double-checked my spelling, so I have the error code commented out.

- I tried updating my plans to include some ideas I thought of to include.

- I left the ninja API as a tree map because I was planning on using another API to generate exercise which I used the pojo generator for. 


I tried finishing the basic flow and useability on the site. I made a quick video to show the basic use of it, and I have some servlets load a user from a dao to see what it would act like when a user is logged in. However, I have been holding off on implementing AWS cognito because I wasn't fully sure how to change the UI design it has. I have sample login and sign-up pages, I like AWS over top of the page design, but I also don't want my logins to look the same. 
[Video](https://www.youtube.com/watch?v=ifXRJNtFzSE)

**Comment by pawaitemadisoncollege** [comment]
Hi @OscarJohnson6 Thanks for the video demo! It was really fun to see all the progress you've made! Wow! You've done a lot of work!

- Regarding Cognito. You can customize the pages to match your site's style. I have not done this, but here is a page with more info: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html. I'm guessing there's a lot of support out there for this as your need is common.
- I gave some feedback about one commented out test in this issue - let me know if that helps: https://github.com/OscarJohnson6/IndieProject/issues/6
- This is somewhat of a nitpick, but I think this package would be better named entity rather than dao (your genericDao is in the database package, which is ok). When I see dao, I'm thinking of the classes that connect to the database... whereas an entity represents a table/the data.
- I'm curious what the coverage is for the HealthCalculations class - it seems like there may be some conditions not covered by the current tests. The fact that I can nitpick about things like this shows how well you have done!

Let me know if you had any questions in any issues that I haven't addressed :)
