### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by OscarJohnson6** [OscarJohnson6/IndieProject#8]
Hi, @pawaitemadisoncollege. The majority of checkpoint 3 is done but I have been having so many errors and troubles with AWS, like I have started getting errors that I never got before.

Thank you for the feedback on Slack, I misunderstood setting up a custom Cognito UI, I thought I could somehow add a link to my website's sign-in page and use that instead of AWS's. For the charges, I did see the discussion which is what made me mention that I was a student but I didn't think/see a full solution was found. I got charged .03$ for a VPC again so if it's fine after this review I am going to delete my Beanstalk instance. 

One question I have is where in the code for auth does it check if the user is signing up or logging in? Otherwise, did what I do here work for adding a user to the database, [Auth class line 230](https://github.com/OscarJohnson6/IndieProject/blob/main/src/main/java/fit/app/controller/Auth.java#L230)? By checking if the user email is in the database and if they are not then the user/email is inserted.

EDIT: The problems listed below I am not worried about and have listed them mostly for documentation purposes.

### Current Problems
- I am not sure how to have/allow optional inputs when a user is signing up with Cognito. I thought custom attributes would work because they aren't required but after researching them more it seems they will actually never show up in the Cognito form and have to be manually set by the developer instead of a user. So I am not sure how to get a user's name, gender, weight, etc. when they sign up. The only idea I've had is to just not care and make the user input that after they made their account; but it kind of takes away the whole point of the site because I wanted a user to be able to quickly input some amounts (like their weight and height) and see what the formula calculations are instead of having to create an account and then be able to input their values.
![customAttributeError](https://github.com/OscarJohnson6/IndieProject/assets/143692207/85d3c518-b233-441c-98bc-8675abdd6a24)

- I accidentally deleted the IAM roles that were made for my Cognito user pools, and now I can't delete the user pools because there is no role with permission attached to it (the error it gives says it's missing permissions). I tried searching it up but I couldn't find a way to recreate an IAM role for a Cognito user pool, so I am stuck with the old user pools.
![awsPoolError](https://github.com/OscarJohnson6/IndieProject/assets/143692207/628a52e3-0130-4faa-98f1-ba96ea69e98f)

### Solved Problems 

- When I click the login button on my cognito form I get the invalid claim exception but I don't understand why because it also says the token can't be used before a specific time, but the specific time is the current time. Like in the screenshot when I clicked log in it was 7:02 pm which is the same time it had in the error message of 19:02:56. I used the debugger and it happens during the code: 
`DecodedJWT jwt = verifier.verify(tokenResponse.getIdToken());`
EDIT: I retryed this about 3 hours later and it works fine now and I don't get the error anymore I have no idea why.
![loginError](https://github.com/OscarJohnson6/IndieProject/assets/143692207/70c1068e-5480-4306-b4c5-9a95b2c54bed)

- I saw other people with the same error enabling the database and it seems it will work once you finish setting up the Beanstalk instance, you just have to add the database afterward. 
![awsDBerror](https://github.com/OscarJohnson6/IndieProject/assets/143692207/ba96a29d-1ac9-473c-846c-42644990519b)

- I am not sure what made the configuration different but to solve this error I had to create an IAM role for elastic Beanstalk with admin permissions. So when setting up the "service access" for Beanstalk I had to use the existing/just created IAM role along with an EC2 key pair and instance profile.
![awsBeanStalkError](https://github.com/OscarJohnson6/IndieProject/assets/143692207/297f100b-ec88-4703-925e-9a13e4625988)

**Comment by pawaitemadisoncollege** [comment]
Hi @OscarJohnson6 - sorry for the long delay in reviewing this!

1. Yes, your technique for adding the user to your database here is spot on: https://github.com/OscarJohnson6/IndieProject/blob/579fae688e0a2a938ce035bd3e276e61ee7d72c5/src/main/java/fit/app/controller/Auth.java#L230-L234
2. To collect additional information from the user - I would do this on a profile page within your application. This way you are storing what you need locally and you don't need to go through cognito to get it. It also makes updating that profile info easy, once the user is logged in.  Another benefit is that if you ever switched to a different auth provider, such as google or fb, you don't have to change anything related to where the profile information is stored/capture. 
3. Claims and the date issue - I have seen this if the date/time on my local computer is "off" by a small amount of time.  Generally synchronizing the clock resolves it. If the problem was on the aws side, maybe  a process synced that time up in the window between when it didn't work and magically started working. 
4. Checkpoint 3 is complete, so if you want to remove your app from aws, you are good to do that now!
